settings:
  title: 'Zonk Status Page'
  url: 'https://zonk.workers.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Services Operational'
  notAllmonitorsOperational: 'Some Services Down'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: sonarr-zonkhome-com # unique identifier
    name: sonarr.zonkhome.com
    description: 'PVR for TV Shows.' # default=empty
    url: 'https://sonarr.zonkhome.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false

  - id: radarr-zonkhome-com # unique identifier
    name: radarr.zonkhome.com
    description: 'PVR for Movies.' # default=empty
    url: 'https://radarr.zonkhome.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false

  - id: trans-zonkhome-com # unique identifier
    name: trans.zonkhome.com
    description: 'A fast and easy BitTorrent client' # default=empty
    url: 'https://trans.zonkhome.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false

  - id: duplicati-zonkhome-com # unique identifier
    name: duplicati.zonkhome.com
    description: 'Free backup software to store encrypted backups online' # default=empty
    url: 'https://duplicati.zonkhome.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false

  - id: adguard-zonkhome-com # unique identifier
    name: adguard.zonkhome.com
    description: 'AdGuard Home is a network-wide software for blocking ads & tracking.' # default=empty
    url: 'https://adguard.zonkhome.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false

  - id: plex-zonkhome-com # unique identifier
    name: plex.zonkhome.com
    description: 'Plex is a global streaming media service and a client–server media player platform.' # default=empty
    url: 'https://plex.zonkhome.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    
  - id: hass-zonkhome-com # unique identifier
    name: hass.zonkhome.com
    description: 'Home Assistant is free and open-source home automation software.' # default=empty
    url: 'https://hass.zonkhome.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
